baseURL = "http://alpinevalues.netlify.com/"
#baseURL = "localhost"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
publishDir = "docs"
theme = "thomasmichaeler-theme"
title = "Alpine Values"
[params]
copyright = "&copy;2016 Markus Töll"
description = "Alpine Values"
email = "hi@thomasmichaeler.com"
sidebarabout = ["Hi, I am Markus."]
[[params.navlinks]]
home = true
name = "{Portfolio}"
url = "portfolio/"
[[params.navlinks]]
name = "About"
url = "about/"
