# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Thomas Michaeler Theme"
license = "MIT"
tags = []
features = []
min_version = 0.1

[author]
  name = "Thomas Michaeler"
  homepage = "https://thomasmichaeler.com/"

# If porting an existing theme
[original]
  name = "Creative portfolio"
  homepage = "https://github.com/kishaningithub/hugo-creative-portfolio-theme"
  license = "MIT"
  licenselink = "https://github.com/kishaningithub/hugo-creative-portfolio-theme/blob/master/LICENSE"
  description = "Port of the creative portfolio theme"
  homepage = "https://github.com/kishaningithub/hugo-creative-portfolio-theme"
  min_version = 0.20